name: assets

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build assets
        run: |
          docker build --build-arg VERSION=${{ github.event.release.tag_name }} -f Dockerfile.assets -t assets .
          docker create --name assets assets
          docker cp assets:/assets assets
          docker rm assets

      - name: Release assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: "assets/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
